// <auto-generated />
using System;
using Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Attendance", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("employeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("present")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("employeeId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Core.Entities.Category", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Core.Entities.Crop", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("farmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("harvestYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("harvestedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("totalRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("unitSellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("farmId");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("Core.Entities.Employee", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("cycleStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("defaultAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("defaultPaymentType")
                        .HasColumnType("int");

                    b.Property<string>("farmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("farmId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Core.Entities.Expense", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("expenseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("farmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("subCategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("farmId");

                    b.HasIndex("subCategoryId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Core.Entities.Farm", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("Core.Entities.Manager", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("Core.Entities.Payment", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("effectivePaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("employeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("periodEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("periodStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("validated")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("employeeId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Core.Entities.QuantityExpense", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("expenseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("initPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("expenseId");

                    b.ToTable("QuantityExpenses");
                });

            modelBuilder.Entity("Core.Entities.RecurringExpense", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("expenseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("expenseId");

                    b.ToTable("RecurringExpenses");
                });

            modelBuilder.Entity("Core.Entities.SubCategory", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("categoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("categoryId");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("FarmManager", b =>
                {
                    b.Property<string>("farmsid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("managersid")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("farmsid", "managersid");

                    b.HasIndex("managersid");

                    b.ToTable("FarmManager");
                });

            modelBuilder.Entity("Core.Entities.Attendance", b =>
                {
                    b.HasOne("Core.Entities.Employee", "employee")
                        .WithMany("attedances")
                        .HasForeignKey("employeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("Core.Entities.Crop", b =>
                {
                    b.HasOne("Core.Entities.Farm", "farm")
                        .WithMany("crops")
                        .HasForeignKey("farmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("farm");
                });

            modelBuilder.Entity("Core.Entities.Employee", b =>
                {
                    b.HasOne("Core.Entities.Farm", "farm")
                        .WithMany("employees")
                        .HasForeignKey("farmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("farm");
                });

            modelBuilder.Entity("Core.Entities.Expense", b =>
                {
                    b.HasOne("Core.Entities.Farm", "farm")
                        .WithMany("expenses")
                        .HasForeignKey("farmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.SubCategory", "subCategory")
                        .WithMany("expenses")
                        .HasForeignKey("subCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("farm");

                    b.Navigation("subCategory");
                });

            modelBuilder.Entity("Core.Entities.Payment", b =>
                {
                    b.HasOne("Core.Entities.Employee", "employee")
                        .WithMany("payments")
                        .HasForeignKey("employeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("Core.Entities.QuantityExpense", b =>
                {
                    b.HasOne("Core.Entities.Expense", "expense")
                        .WithMany("QuantityExpenses")
                        .HasForeignKey("expenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("expense");
                });

            modelBuilder.Entity("Core.Entities.RecurringExpense", b =>
                {
                    b.HasOne("Core.Entities.Expense", "expense")
                        .WithMany("RecurringExpenses")
                        .HasForeignKey("expenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("expense");
                });

            modelBuilder.Entity("Core.Entities.SubCategory", b =>
                {
                    b.HasOne("Core.Entities.Category", "category")
                        .WithMany("subCategories")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("FarmManager", b =>
                {
                    b.HasOne("Core.Entities.Farm", null)
                        .WithMany()
                        .HasForeignKey("farmsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Manager", null)
                        .WithMany()
                        .HasForeignKey("managersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Category", b =>
                {
                    b.Navigation("subCategories");
                });

            modelBuilder.Entity("Core.Entities.Employee", b =>
                {
                    b.Navigation("attedances");

                    b.Navigation("payments");
                });

            modelBuilder.Entity("Core.Entities.Expense", b =>
                {
                    b.Navigation("QuantityExpenses");

                    b.Navigation("RecurringExpenses");
                });

            modelBuilder.Entity("Core.Entities.Farm", b =>
                {
                    b.Navigation("crops");

                    b.Navigation("employees");

                    b.Navigation("expenses");
                });

            modelBuilder.Entity("Core.Entities.SubCategory", b =>
                {
                    b.Navigation("expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
